### ISSUE TITLE
Unable to instantiate appComponentFactory

### ISSUE THREAD

**Issue by musabgelisgen** [mapbox/mapbox-android-demo#1296]
When I clone this project, build and finally try to run, it gives the following error and the app crashes immediately. I searched the issues section and nobody had the same issue. Sorry that I am new to Android development so it might be an easy fix. Any ideas on fixing this?

```
E/LoadedApk: Unable to instantiate appComponentFactory
    java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxandroiddemo.debug.placeholderString" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86, /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/base.apk!/lib/x86, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.LoadedApk.createAppFactory(LoadedApk.java:226)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:731)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:810)
        at android.app.LoadedApk.getResources(LoadedApk.java:1032)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2345)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5749)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/MultiDex: VM with version 2.1.0 has multidex support
    Installing application
    VM has multidex support, MultiDex support library is disabled.
W/FirebaseApp: Default FirebaseApp failed to initialize because no default options were found. This usually means that com.google.gms:google-services was not applied to your gradle project.
I/FirebaseInitProvider: FirebaseApp initialization unsuccessful
I/CrashlyticsInitProvider: CrashlyticsInitProvider skipping initialization
W/Settings: Setting airplane_mode_on has moved from android.provider.Settings.System to android.provider.Settings.Global, returning read-only value.
D/SoLoader: init start
D/SoLoader: adding system library source: /vendor/lib
D/SoLoader: adding system library source: /system/lib
D/SoLoader: adding application source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86 flags = 0]
D/SoLoader: adding backup source from : com.facebook.soloader.ApkSoSource[root = /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main flags = 1]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /system/lib flags = 2]
D/SoLoader: Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /vendor/lib flags = 2]
    Preparing SO source: com.facebook.soloader.DirectorySoSource[root = /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86 flags = 0]
    Preparing SO source: com.facebook.soloader.ApkSoSource[root = /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main flags = 1]
V/fb-UnpackingSoSource: locked dso store /data/user/0/com.mapbox.mapboxandroiddemo.debug/lib-main
I/fb-UnpackingSoSource: dso store is up-to-date: /data/user/0/com.mapbox.mapboxandroiddemo.debug/lib-main
V/fb-UnpackingSoSource: releasing dso store lock for /data/user/0/com.mapbox.mapboxandroiddemo.debug/lib-main
D/SoLoader: init finish: 4 SO sources prepared
    init exiting
D/SoLoader: About to load: libmapbox-gl.so
D/SoLoader: libmapbox-gl.so found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
D/SoLoader: Loading lib dependencies: [libEGL.so, libGLESv2.so, libandroid.so, libjnigraphics.so, liblog.so, libz.so, libm.so, libdl.so, libc.so]
D/SoLoader: About to load: libEGL.so
    libEGL.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libEGL.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libEGL.so not found on /vendor/lib
    libEGL.so found on /system/lib
    libEGL.so loaded implicitly
    Loaded: libEGL.so
    About to load: libGLESv2.so
D/SoLoader: libGLESv2.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libGLESv2.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
D/SoLoader: libGLESv2.so not found on /vendor/lib
    libGLESv2.so found on /system/lib
    libGLESv2.so loaded implicitly
    Loaded: libGLESv2.so
    About to load: libandroid.so
    libandroid.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libandroid.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libandroid.so not found on /vendor/lib
    libandroid.so found on /system/lib
D/SoLoader: libandroid.so loaded implicitly
    Loaded: libandroid.so
    About to load: libjnigraphics.so
    libjnigraphics.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libjnigraphics.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libjnigraphics.so not found on /vendor/lib
    libjnigraphics.so found on /system/lib
    libjnigraphics.so loaded implicitly
    Loaded: libjnigraphics.so
D/SoLoader: About to load: liblog.so
    liblog.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    liblog.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    liblog.so not found on /vendor/lib
    liblog.so found on /system/lib
    liblog.so loaded implicitly
    Loaded: liblog.so
    About to load: libz.so
    libz.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
D/SoLoader: libz.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libz.so not found on /vendor/lib
    libz.so found on /system/lib
    libz.so loaded implicitly
    Loaded: libz.so
    About to load: libm.so
    libm.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libm.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libm.so not found on /vendor/lib
    libm.so found on /system/lib
    libm.so loaded implicitly
    Loaded: libm.so
    About to load: libdl.so
D/SoLoader: libdl.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libdl.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
    libdl.so not found on /vendor/lib
    libdl.so found on /system/lib
    libdl.so loaded implicitly
D/SoLoader: Loaded: libdl.so
    About to load: libc.so
D/SoLoader: libc.so not found on /data/data/com.mapbox.mapboxandroiddemo.debug/lib-main
    libc.so not found on /data/app/com.mapbox.mapboxandroiddemo.debug-nNeDEx4iIHcmPAN22HFYvg==/lib/x86
D/SoLoader: libc.so not found on /vendor/lib
    libc.so found on /system/lib
    libc.so loaded implicitly
    Loaded: libc.so
W/System.err: java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/com.mapbox.mapboxandroiddemo.debug/lib-main/libmapbox-gl.so" has unexpected e_machine: 40 (EM_ARM)
        at java.lang.Runtime.load0(Runtime.java:928)
        at java.lang.System.load(System.java:1633)
        at com.facebook.soloader.SoLoader$1.load(SoLoader.java:393)
W/System.err:     at com.facebook.soloader.DirectorySoSource.loadLibraryFrom(DirectorySoSource.java:77)
        at com.facebook.soloader.UnpackingSoSource.loadLibrary(UnpackingSoSource.java:458)
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:731)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
W/System.err:     at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:42)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.mapbox.mapboxandroiddemo.MapboxApplication.onCreate(MapboxApplication.java:25)
W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
E/SoLoader: couldn't find DSO to load: libmapbox-gl.so caused by: dlopen failed: "/data/data/com.mapbox.mapboxandroiddemo.debug/lib-main/libmapbox-gl.so" has unexpected e_machine: 40 (EM_ARM)
E/Mbgl-LibraryLoader: Failed to load native shared library.
    com.facebook.soloader.SoLoader$WrongAbiError: APK was built for a different platform
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:645)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525)
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:42)
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.mapbox.mapboxandroiddemo.MapboxApplication.onCreate(MapboxApplication.java:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.UnsatisfiedLinkError: couldn't find DSO to load: libmapbox-gl.so caused by: dlopen failed: "/data/data/com.mapbox.mapboxandroiddemo.debug/lib-main/libmapbox-gl.so" has unexpected e_machine: 40 (EM_ARM)
        at com.facebook.soloader.SoLoader.doLoadLibraryBySoName(SoLoader.java:789)
        at com.facebook.soloader.SoLoader.loadLibraryBySoName(SoLoader.java:639)
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:577) 
        at com.facebook.soloader.SoLoader.loadLibrary(SoLoader.java:525) 
        at com.mapbox.mapboxsdk.module.loader.LibraryLoaderProviderImpl$SoLibraryLoader.load(LibraryLoaderProviderImpl.java:42) 
        at com.mapbox.mapboxsdk.LibraryLoader.load(LibraryLoader.java:43) 
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<clinit>(NativeConnectivityListener.java:13) 
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43) 
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67) 
        at com.mapbox.mapboxandroiddemo.MapboxApplication.onCreate(MapboxApplication.java:25) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
E/droiddemo.debu: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxandroiddemo.debug, PID: 10973
    java.lang.UnsatisfiedLinkError: No implementation found for void com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize() (tried Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize and Java_com_mapbox_mapboxsdk_net_NativeConnectivityListener_initialize__)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.initialize(Native Method)
        at com.mapbox.mapboxsdk.net.NativeConnectivityListener.<init>(NativeConnectivityListener.java:27)
        at com.mapbox.mapboxsdk.net.ConnectivityReceiver.instance(ConnectivityReceiver.java:43)
        at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:67)
        at com.mapbox.mapboxandroiddemo.MapboxApplication.onCreate(MapboxApplication.java:25)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process: Sending signal. PID: 10973 SIG: 9
Process 10973 terminated.
```

**Comment by langsmith** [comment]
Have you adjusted any code in the project before trying to run it?

I don't _think_ it'll make a difference based on your crash text above, but did you set a Mapbox token? https://github.com/mapbox/mapbox-android-demo#setting-the-mapbox-access-token

After you:
- Try a clean uninstall of the app on your device.
- `File` –> `Invalidate Caches / Restart` in Android Studio.
- `Build` –> `Clean Project` in Android Studio. 

Do you still get the crash?

**Comment by langsmith** [comment]
Closing this because I haven't heard back. More than happy to reopen this ticket and continue the conversation if I hear back.

**Comment by Oki-LM7** [comment]
It happened to me just now. The solution is by adding the mapview id in the xml.

<com.mapbox.mapboxsdk.maps.MapView
android:id="@+id/mapView"
android:layout_width="match_parent"
android:layout_height="match_parent"
/>
