### ISSUE TITLE
App builds, but crashes on launch

### ISSUE THREAD

**Issue by pwicks86** [mapbox/mapbox-android-demo#1386]
When I try to build the app in Android Studio, it builds fine, but then crashes on launch. 

```
10-09 16:04:32.124 18415 18415 D AndroidRuntime: Shutting down VM
10-09 16:04:32.125 18415 18415 E AndroidRuntime: FATAL EXCEPTION: main
10-09 16:04:32.125 18415 18415 E AndroidRuntime: Process: com.mapbox.mapboxandroiddemo, PID: 18415
10-09 16:04:32.125 18415 18415 E AndroidRuntime: java.lang.RuntimeException: Unable to instantiate application com.mapbox.mapboxandroiddemo.MapboxApplication: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxandroiddemo.MapboxApplication" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1226)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6431)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.ActivityThread.access$1300(ActivityThread.java:219)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:214)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7356)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.mapboxandroiddemo.MapboxApplication" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo-cpPjB9cOTuR17EMI07iq9w==/base.apk!/lib/arm64-v8a, /system/lib64, /product/lib64]]
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1155)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:1218)
10-09 16:04:32.125 18415 18415 E AndroidRuntime: 	... 9 more
```

Phone: Pixel 4 XL
Android Version: 10
Android Studio Version: 4.2 Canary 13
Build Variant: globalDebug

Am I missing something?

**Comment by pwicks86** [comment]
Ah, figured it out, it looks like the `MapboxAndroidWearDemo` configuration is selected by default and I was using a device with no Android Wear device.
