### ISSUE TITLE
Wear app crashes in emulator

### ISSUE THREAD

**Issue by Guardiola31337** [mapbox/mapbox-android-demo#234]
Running Wear demo app in an emulator (Android Wear Round API 25).

### Steps to trigger behavior

 1. Open the app
 2. Tap on A simple map view
 3. Go back
 4. App crashes

### Expected behavior

App doesn't crash

### Actual behavior

App crashes

![wearcrash](https://cloud.githubusercontent.com/assets/1668582/23947423/03a9c4b8-097f-11e7-9803-6d28e9515087.gif)

### Logcat

```
03-15 07:26:12.547 11007 11007 D ViewRootImpl[SimpleMapViewActivity]: changeCanvasOpacity: opaque=false
03-15 07:26:12.564  1252  1297 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-15 07:26:12.565  1252  1297 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-15 07:26:12.570  1252  1297 D gralloc_ranchu: gralloc_alloc: format 1 and usage 0x900 imply creation of host color buffer
03-15 07:26:12.614 11007 11023 E EGL_emulation: tid 11023: eglSurfaceAttrib(1174): error 0x3009 (EGL_BAD_MATCH)
03-15 07:26:12.619 11007 11023 W OpenGLRenderer: Failed to set EGL_SWAP_BEHAVIOR on surface 0x91650c00, error=EGL_BAD_MATCH
03-15 07:26:12.757 11007 11007 D ViewRootImpl[SimpleMapViewActivity]: changeCanvasOpacity: opaque=false
03-15 07:26:13.089 11007 11007 D mbgl    : {androidweardemo}[JNI]: nativeDestroySurface
03-15 07:26:13.101  1252  1252 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-15 07:26:13.117  1252  1252 W SurfaceFlinger: couldn't log to binary event log: overflow.
03-15 07:26:13.126 11007 11007 D mbgl    : {androidweardemo}[JNI]: nativeTerminateContext
03-15 07:26:13.126 11007 11007 D mbgl    : {androidweardemo}[JNI]: nativeTerminateDisplay
03-15 07:26:13.126 11007 11007 D mbgl    : {androidweardemo}[JNI]: nativeDestroySurface
03-15 07:26:13.126 11007 11007 D mbgl    : {androidweardemo}[JNI]: nativeDestroy
03-15 07:26:13.126 11007 11007 I mbgl    : {androidweardemo}[Android]: Not activating as we are not ready
03-15 07:26:13.164 11007 11007 I mbgl    : {androidweardemo}[Android]: Not deactivating as we are not ready
03-15 07:26:13.173 11007 11007 E libEGL  : call to OpenGL ES API with no current context (logged once per thread)
03-15 07:26:13.173 11007 11007 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 11007 (androidweardemo)
03-15 07:26:13.173  1208  1208 W         : debuggerd: handling request: pid=11007 uid=10042 gid=10042 tid=11007
03-15 07:26:13.234 11192 11192 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-15 07:26:13.234 11192 11192 F DEBUG   : Build fingerprint: 'generic_x86/sdk_google_aw_x86/generic_x86:7.1.1/N7G12V/3746635:userdebug/dev-keys'
03-15 07:26:13.234 11192 11192 F DEBUG   : Revision: '0'
03-15 07:26:13.234 11192 11192 F DEBUG   : ABI: 'x86'
03-15 07:26:13.235 11192 11192 F DEBUG   : pid: 11007, tid: 11007, name: androidweardemo  >>> com.mapbox.mapboxandroidweardemo <<<
03-15 07:26:13.235 11192 11192 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
03-15 07:26:13.235 11192 11192 F DEBUG   :     eax 95473fd0  ebx 9546fff4  ecx 000000bf  edx 927eb2fc
03-15 07:26:13.235 11192 11192 F DEBUG   :     esi 9df3de00  edi 927eb000
03-15 07:26:13.235 11192 11192 F DEBUG   :     xcs 00000073  xds 0000007b  xes 0000007b  xfs 0000003b  xss 0000007b
03-15 07:26:13.235 11192 11192 F DEBUG   :     eip 00000000  ebp 00000000  esp bfc61bfc  flags 00010202
03-15 07:26:13.236 11192 11192 F DEBUG   :
03-15 07:26:13.236 11192 11192 F DEBUG   : backtrace:
03-15 07:26:13.236 11192 11192 F DEBUG   :     #00 pc 00000000  <unknown>
03-15 07:26:13.938  1567  1597 I BootReceiver: Copying /data/tombstones/tombstone_01 to DropBox (SYSTEM_TOMBSTONE)
03-15 07:26:13.941  1208  1208 W         : debuggerd: resuming target 11007
03-15 07:26:13.950  1567 11209 W ActivityManager:   Force finishing activity com.mapbox.mapboxandroidweardemo/.MainActivity
03-15 07:26:13.970  1567  1600 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 60)
03-15 07:26:13.971  1567 11209 E JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 104)
03-15 07:26:13.971  1567 11209 W ActivityManager: Exception thrown during pause
03-15 07:26:13.971  1567 11209 W ActivityManager: android.os.DeadObjectException: Transaction failed on small parcel; remote process probably died
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:615)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:785)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1141)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3523)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3359)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13495)
03-15 07:26:13.971  1567 11209 W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
03-15 07:26:13.974  1250  1250 E lowmemorykiller: Error writing /proc/11007/oom_score_adj; errno=22
03-15 07:26:13.974  1567 11209 W ActivityManager: Failed setting process group of 11007 to 1
03-15 07:26:13.974  1567 11209 W System.err: java.lang.IllegalArgumentException: Given thread 11023 does not exist
03-15 07:26:13.975  1567 11209 W System.err: 	at android.os.Process.setThreadPriority(Native Method)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityManagerService.applyOomAdjLocked(ActivityManagerService.java:20533)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityManagerService.updateOomAdjLocked(ActivityManagerService.java:21035)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityInnerLocked(ActivityStack.java:2447)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStack.resumeTopActivityUncheckedLocked(ActivityStack.java:2127)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1833)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStackSupervisor.resumeFocusedStackTopActivityLocked(ActivityStackSupervisor.java:1823)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:1196)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:3523)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:3359)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:1855)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.AppErrors.handleAppCrashLocked(AppErrors.java:619)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.AppErrors.makeAppCrashingLocked(AppErrors.java:477)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.AppErrors.crashApplicationInner(AppErrors.java:353)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.AppErrors.crashApplication(AppErrors.java:305)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:13495)
03-15 07:26:13.975  1567 11209 W System.err: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
03-15 07:26:13.991  1567  1662 W InputDispatcher: channel 'b38b524 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-15 07:26:13.991  1567  1662 E InputDispatcher: channel 'b38b524 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-15 07:26:13.992  1567  1662 W InputDispatcher: channel '7e8fdf9 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-15 07:26:13.992  1567  1662 E InputDispatcher: channel '7e8fdf9 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-15 07:26:13.992  1567  1662 W InputDispatcher: channel 'f60111c Panel:com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
03-15 07:26:13.992  1567  1662 E InputDispatcher: channel 'f60111c Panel:com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
03-15 07:26:13.993  1268  1268 I Zygote  : Process 11007 exited due to signal (11)
03-15 07:26:13.994  1567  1579 D GraphicsStats: Buffer count: 3
03-15 07:26:13.996  1567  1815 I ActivityManager: Process com.mapbox.mapboxandroidweardemo (pid 11007) has died
03-15 07:26:13.996  1567  1815 D ActivityManager: cleanUpApplicationRecord -- 11007
03-15 07:26:13.998  1567  1815 W ActivityManager: Scheduling restart of crashed service com.mapbox.mapboxandroidweardemo/com.mapbox.services.android.telemetry.service.TelemetryService in 1000ms
03-15 07:26:13.999  1567  1578 I WindowManager: WIN DEATH: Window{f60111c u0 Panel:com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity}
03-15 07:26:13.999  1567  1578 W InputDispatcher: Attempted to unregister already unregistered input channel 'f60111c Panel:com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)'
03-15 07:26:14.002  1567  2034 I WindowManager: WIN DEATH: Window{9d7f94c u0 SurfaceView - com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity}
03-15 07:26:14.003  1567  3557 I WindowManager: WIN DEATH: Window{7e8fdf9 u0 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity}
03-15 07:26:14.003  1567  3557 W InputDispatcher: Attempted to unregister already unregistered input channel '7e8fdf9 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.examples.SimpleMapViewActivity (server)'
03-15 07:26:14.008  1567  1696 I WindowManager: WIN DEATH: Window{b38b524 u0 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.MainActivity}
03-15 07:26:14.008  1567  1696 W InputDispatcher: Attempted to unregister already unregistered input channel 'b38b524 com.mapbox.mapboxandroidweardemo/com.mapbox.mapboxandroidweardemo.MainActivity (server)'
```

👀  @cammace

**Comment by Guardiola31337** [comment]
Fixed with #235.
