### ISSUE TITLE
Crash On 2.2.0

### ISSUE THREAD

**Issue by bleege** [mapbox/mapbox-android-demo#44]
[From Crashlytics](https://fabric.io/mapbox4/android/apps/com.mapbox.mapboxandroiddemo/issues/56464834f5d3a7f76b8d787b):

![screen shot 2015-11-13 at 3 27 03 pm](https://cloud.githubusercontent.com/assets/989928/11158046/0fc80622-8a1b-11e5-9dea-8d7338e09c5d.png)

```java
Fatal Exception: java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:251)
       at java.util.ArrayList.get(ArrayList.java:304)
       at com.mapbox.mapboxandroiddemo.MainActivity$1.onTouch(MainActivity.java:60)
       at android.view.View.dispatchTouchEvent(View.java:7257)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2235)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1932)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2241)
       at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1904)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1968)
       at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1420)
       at android.app.Activity.dispatchTouchEvent(Activity.java:2428)
       at android.support.v7.internal.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:60)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1916)
       at android.view.View.dispatchPointerEvent(View.java:7442)
       at android.view.ViewRootImpl.deliverPointerEvent(ViewRootImpl.java:3610)
       at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:3538)
       at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:4790)
       at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:4750)
       at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:4902)
       at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:179)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:125)
       at android.os.Looper.loop(Looper.java:140)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by cammace** [comment]
App code has changed significantly, closing!
