### ISSUE TITLE
Fix SymbolLayer RecyclerView marker/card click crash

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#507]
The SymbolLayer/Recyclerview interaction example crashes when a marker or a recyclerview card is selected 

Seems that [the marker object here is null](https://github.com/mapbox/mapbox-android-demo/blob/93f8c37b6b07955fe6c574f82090dcc197b6f49c/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/labs/RecyclerViewSymbolLayerActivity.java#L330)

The crash 👇  

```java
10-19 16:23:06.206 6959-6959/com.mapbox.mapboxandroiddemo.debug E/UncaughtException: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.style.layers.SymbolLayer.setProperties(com.mapbox.mapboxsdk.style.layers.PropertyValue[])' on a null object reference
                                                                                         at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$2.onAnimationUpdate(RecyclerViewSymbolLayerActivity.java:330)
                                                                                         at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1350)
                                                                                         at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
                                                                                         at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:581)
                                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:1005)
                                                                                         at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
                                                                                         at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity.selectMarker(RecyclerViewSymbolLayerActivity.java:335)
                                                                                         at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity.onMarkerClickHandler(RecyclerViewSymbolLayerActivity.java:384)
                                                                                         at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$LocationRecyclerViewAdapter$1.onClick(RecyclerViewSymbolLayerActivity.java:258)
                                                                                         at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$LocationRecyclerViewAdapter$MyViewHolder.onClick(RecyclerViewSymbolLayerActivity.java:289)
                                                                                         at android.view.View.performClick(View.java:5669)
                                                                                         at android.view.View$PerformClick.run(View.java:22546)
                                                                                         at android.os.Handler.handleCallback(Handler.java:751)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
10-19 16:23:06.211 6959-6982/com.mapbox.mapboxandroiddemo.debug E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
10-19 16:23:06.499 6959-6959/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                  Process: com.mapbox.mapboxandroiddemo.debug, PID: 6959
                                                                                  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.mapbox.mapboxsdk.style.layers.SymbolLayer.setProperties(com.mapbox.mapboxsdk.style.layers.PropertyValue[])' on a null object reference
                                                                                      at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$2.onAnimationUpdate(RecyclerViewSymbolLayerActivity.java:330)
                                                                                      at android.animation.ValueAnimator.animateValue(ValueAnimator.java:1350)
                                                                                      at android.animation.ValueAnimator.setCurrentFraction(ValueAnimator.java:615)
                                                                                      at android.animation.ValueAnimator.setCurrentPlayTime(ValueAnimator.java:581)
                                                                                      at android.animation.ValueAnimator.start(ValueAnimator.java:1005)
                                                                                      at android.animation.ValueAnimator.start(ValueAnimator.java:1014)
                                                                                      at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity.selectMarker(RecyclerViewSymbolLayerActivity.java:335)
                                                                                      at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity.onMarkerClickHandler(RecyclerViewSymbolLayerActivity.java:384)
                                                                                      at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$LocationRecyclerViewAdapter$1.onClick(RecyclerViewSymbolLayerActivity.java:258)
                                                                                      at com.mapbox.mapboxandroiddemo.labs.RecyclerViewSymbolLayerActivity$LocationRecyclerViewAdapter$MyViewHolder.onClick(RecyclerViewSymbolLayerActivity.java:289)
                                                                                      at android.view.View.performClick(View.java:5669)
                                                                                      at android.view.View$PerformClick.run(View.java:22546)
                                                                                      at android.os.Handler.handleCallback(Handler.java:751)
                                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                      at android.os.Looper.loop(Looper.java:154)
                                                                                      at android.app.ActivityThread.main(ActivityThread.java:6334)
                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
```

**Comment by langsmith** [comment]
fixed by #538
