### ISSUE TITLE
Fix wearable map fragment example crashing on open

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#566]
Fragment example crashes on trying to open it
![ezgif com-resize 1](https://user-images.githubusercontent.com/4394910/33495150-18e40e88-d67a-11e7-93fa-4702044e31ff.gif)

```java
10-24 15:17:27.465 4625-4625/com.mapbox.mapboxandroiddemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                            Process: com.mapbox.mapboxandroiddemo, PID: 4625
                                                                            java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
                                                                                at java.lang.Class.newInstance(Native Method)
                                                                                at android.app.Instrumentation.newActivity(Instrumentation.java:1078)
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557)
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                at android.os.Looper.loop(Looper.java:154)
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                                at java.lang.reflect.Method.invoke(Native Method)
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
                                                                             Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/system/framework/com.google.android.wearable.jar", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/base.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_dependencies_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_0_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_1_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_2_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_3_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_4_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_5_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_6_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_7_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_8_apk.apk", zip file "/data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-1/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/base.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_dependencies_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_0_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_1_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_2_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_3_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_4_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_5_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_6_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_7_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_8_apk.apk!/lib/x86, /data/app/com.mapbox.mapboxandroiddemo-1/split_lib_slice_9_apk.apk!/lib/x86, /system/lib, /vendor/lib]]
                                                                                at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                                                                                at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                at java.lang.Class.newInstance(Native Method) 
                                                                                at android.app.Instrumentation.newActivity(Instrumentation.java:1078) 
                                                                                at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2557) 
                                                                                at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726) 
                                                                                at android.app.ActivityThread.-wrap12(ActivityThread.java) 
                                                                                at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477) 
                                                                                at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                at android.os.Looper.loop(Looper.java:154) 
                                                                                at android.app.ActivityThread.main(ActivityThread.java:6119) 
                                                                                at java.lang.reflect.Method.invoke(Native Method) 
                                                                                at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886) 
                                                                                at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776) 
```

_**Wear dependencies**_

![screen shot 2017-12-01 at 9 30 44 am](https://user-images.githubusercontent.com/4394910/33495225-67522d3e-d67a-11e7-949a-5fd49368d2d9.png)
![screen shot 2017-12-01 at 9 30 39 am](https://user-images.githubusercontent.com/4394910/33495226-676ed09c-d67a-11e7-8d6f-6dcee5316e52.png)

**Comment by langsmith** [comment]
Fixed with https://github.com/mapbox/mapbox-android-demo/commit/8685c144abdb4d9c0c3e1295545063afc33ad331 by removing location related code. I felt that getting the location wasn't related to simply showing a map fragment...
