### ISSUE TITLE
PID: 25893 java.lang.NoClassDefFoundError: Failed resolution of:

### ISSUE THREAD

**Issue by ShaldonSwiidAppDesigns** [mapbox/mapbox-android-demo#572]
Can someone help me or advise me? I followed the steps in this demo, however everytime I run my app I get this error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: swiidappdesigns.haveasafetrip, PID: 25893
                  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/android/telemetry/location/LostLocationEngine;
                      at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17)
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44)
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23)
                      at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54)
                      at swiidappdesigns.haveasafetrip.MapsScreen.onCreate(MapsScreen.java:85)
                      at android.app.Activity.performCreate(Activity.java:6912)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
                      at android.app.ActivityThread.-wrap14(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6692)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                   Caused by: java.lang.ClassNotFoundException: com.mapbox.services.android.telemetry.location.LostLocationEngine
                      at java.lang.VMClassLoader.findLoadedClass(Native Method)
                      at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:742)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:362)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
                      at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
                      at swiidappdesigns.haveasafetrip.MapsScreen.onCreate(MapsScreen.java:85) 
                      at android.app.Activity.performCreate(Activity.java:6912) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6692) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
                   Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapzen/android/lost/api/LostApiClient$ConnectionCallbacks;
                      at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
                      at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
                      at swiidappdesigns.haveasafetrip.MapsScreen.onCreate(MapsScreen.java:85) 
                      at android.app.Activity.performCreate(Activity.java:6912) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6692) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapzen.android.lost.api.LostApiClient$ConnectionCallbacks" on path: DexPathList[[zip file "/data/app/swiidappdesigns.haveasafetrip-2/base.apk"],nativeLibraryDirectories=[/data/app/swiidappdesigns.haveasafetrip-2/lib/arm64, /data/app/swiidappdesigns.haveasafetrip-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                      at com.mapbox.services.android.telemetry.location.LostLocationEngineFactory.supply(LostLocationEngineFactory.java:17) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:44) 
                      at com.mapbox.services.android.telemetry.location.LocationEngineProvider.<init>(LocationEngineProvider.java:23) 
                      at com.mapbox.mapboxsdk.Mapbox.getInstance(Mapbox.java:54) 
                      at swiidappdesigns.haveasafetrip.MapsScreen.onCreate(MapsScreen.java:85) 
                      at android.app.Activity.performCreate(Activity.java:6912) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985) 
                      at android.app.ActivityThread.-wrap14(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6692) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 
Application terminated.

The following is what my code looks like:
```
import android.content.Intent;
import android.content.pm.PackageManager;
import android.location.Location;
import android.support.annotation.NonNull;
import android.support.design.widget.NavigationView;
import android.support.v4.app.ActivityCompat;
import android.support.v4.view.GravityCompat;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AlertDialog;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.view.Menu;
import android.view.MenuItem;
import android.support.v7.widget.Toolbar;
import android.webkit.PermissionRequest;
import android.widget.ArrayAdapter;
import android.widget.ListView;
import android.widget.TextView;
import android.widget.Toast;

import com.firebase.ui.auth.AuthUI;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;
import com.google.firebase.auth.FirebaseAuth;
import com.google.firebase.database.DataSnapshot;
import com.google.firebase.database.DatabaseError;
import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;
import com.google.firebase.database.ValueEventListener;

import com.mapbox.mapboxsdk.Mapbox;
import com.mapbox.mapboxsdk.annotations.MarkerOptions;
import com.mapbox.mapboxsdk.camera.CameraPosition;
import com.mapbox.mapboxsdk.camera.CameraUpdate;
import com.mapbox.mapboxsdk.camera.CameraUpdateFactory;
import com.mapbox.mapboxsdk.geometry.LatLng;
import com.mapbox.mapboxsdk.geometry.LatLngBounds;
import com.mapbox.mapboxsdk.maps.MapView;
import com.mapbox.mapboxsdk.maps.MapboxMap;
import com.mapbox.mapboxsdk.maps.OnMapReadyCallback;
import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerMode;
import com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin;

import com.mapbox.services.android.location.LostLocationEngine;
import com.mapbox.services.android.telemetry.location.LocationEngine;
import com.mapbox.services.android.telemetry.location.LocationEngineListener;
import com.mapbox.services.android.telemetry.location.LocationEnginePriority;
import com.mapbox.services.android.telemetry.permissions.PermissionsListener;
import com.mapbox.services.android.telemetry.permissions.PermissionsManager;

import java.util.Arrays;
import java.util.List;
import java.util.Map;

import static com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerMode.NAVIGATION;

public class MapsScreen extends AppCompatActivity implements LocationEngineListener, PermissionsListener {


    //Firebase declarations
    private FirebaseAuth mAuth;
    private FirebaseAuth.AuthStateListener mAuthListener;
    private FirebaseDatabase database;

    private DatabaseReference myDBRef;

    //Mapbox declarations
    private MapView mapView;
    private MapboxMap mapboxMap;
    private LocationEngine locationEngine;
    private LocationLayerPlugin locationLayerPlugin;
    private PermissionsManager permissionsManager;

    //The following is for the nav drawer
    private DrawerLayout navDrawer;
    private ActionBarDrawerToggle navDrawerToggle;
    private NavigationView navViewLayout;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Mapbox.getInstance(this, getString(R.string.access_token));
        setContentView(R.layout.activity_maps_screen);

        //The following is for Firebase
        mAuth = FirebaseAuth.getInstance();

        //The following is for the map
        mapView = (MapView) findViewById(R.id.mapView);
        mapView.onCreate(savedInstanceState);
        mapView.getMapAsync(new OnMapReadyCallback() {
            @Override
            public void onMapReady(MapboxMap mapboxMap) {
                MapsScreen.this.mapboxMap = mapboxMap;
                enableLocationPlugin();

            }
        });


        //The following is for the nav drawer
        navDrawer = (DrawerLayout)findViewById(R.id.activity_maps_screen);
        navDrawerToggle = new ActionBarDrawerToggle(this, navDrawer,R.string.navigation_drawer_open,R.string.navigation_drawer_close);
        navDrawerToggle.setDrawerIndicatorEnabled(true);
        navDrawer.addDrawerListener(navDrawerToggle);
        navDrawerToggle.syncState();
        getSupportActionBar().setDisplayHomeAsUpEnabled(true);

        //The following adds the avatar from the db to the NavProfileAvatar


        //The following is the continuation for the nav drawer
        navViewLayout = (NavigationView)findViewById(R.id.nav_view_layout);
        navViewLayout.setNavigationItemSelectedListener(new NavigationView.OnNavigationItemSelectedListener() {
            @Override
            public boolean onNavigationItemSelected(@NonNull MenuItem item) {
                int id = item.getItemId();
                if(id == R.id.nav_item_edit_profile){
                    startActivity(new Intent(MapsScreen.this, Profile.class));
                } else if(id == R.id.nav_item_book_a_trip){

                } else if(id == R.id.nav_item_pricing){

                } else if(id == R.id.nav_item_sign_out){
                    signMeOut();
                } else if(id == R.id.nav_item_help){

                }
                return true;
            }
        });


    }

    public void signMeOut(){
        AuthUI.getInstance()
                .signOut(this)
                .addOnCompleteListener(new OnCompleteListener<Void>() {
                    public void onComplete(@NonNull Task<Void> task) {
                        // user is now signed out
                        startActivity(new Intent(MapsScreen.this, SplashScreen.class));
                        finish();
                    }
                });
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        if (navDrawerToggle.onOptionsItemSelected(item))
            return true;

        return super.onOptionsItemSelected(item);

    }

    //The following is for the Mapbox
    @Override
    public void onResume() {
        super.onResume();
        mapView.onResume();
    }

    @Override
    @SuppressWarnings( {"MissingPermission"})
    protected void onStart() {
        super.onStart();
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStart();
        }
        mapView.onStart();
    }

    @Override
    protected void onStop() {
        super.onStop();
        if (locationEngine != null) {
            locationEngine.removeLocationUpdates();
        }
        if (locationLayerPlugin != null) {
            locationLayerPlugin.onStop();
        }
        mapView.onStop();
    }

    @Override
    public void onPause() {
        super.onPause();
        mapView.onPause();
    }

    @Override
    public void onSaveInstanceState(Bundle outState) {
        super.onSaveInstanceState(outState);
        mapView.onSaveInstanceState(outState);
    }

    @Override
    public void onLowMemory() {
        super.onLowMemory();
        mapView.onLowMemory();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        mapView.onDestroy();
        if (locationEngine != null) {
            locationEngine.deactivate();
        }
    }

    @SuppressWarnings( {"MissingPermission"})
    private void enableLocationPlugin() {
        // Check if permissions are enabled and if not request
        if (PermissionsManager.areLocationPermissionsGranted(this)) {
            // Create an instance of LOST location engine
            initializeLocationEngine();

            locationLayerPlugin = new LocationLayerPlugin(mapView, mapboxMap, locationEngine);
            locationLayerPlugin.setLocationLayerEnabled(LocationLayerMode.TRACKING);
        } else {
            permissionsManager = new PermissionsManager(this);
            permissionsManager.requestLocationPermissions(this);
        }
    }

    @SuppressWarnings( {"MissingPermission"})
    private void initializeLocationEngine() {
        locationEngine = new LostLocationEngine(MapsScreen.this);
        locationEngine.setPriority(LocationEnginePriority.HIGH_ACCURACY);
        locationEngine.activate();

        Location lastLocation = locationEngine.getLastLocation();
        if (lastLocation != null) {
            setCameraPosition(lastLocation);
        } else {
            locationEngine.addLocationEngineListener(this);
        }
    }

    private void setCameraPosition(Location location) {
        mapboxMap.animateCamera(CameraUpdateFactory.newLatLngZoom(
                new LatLng(location.getLatitude(), location.getLongitude()), 16));
    }

    @Override
    public void onRequestPermissionsResult(int requestCode, @NonNull String[] permissions, @NonNull int[] grantResults) {
        permissionsManager.onRequestPermissionsResult(requestCode, permissions, grantResults);
    }

    @Override
    public void onExplanationNeeded(List<String> permissionsToExplain) {

    }

    @Override
    public void onPermissionResult(boolean granted) {
        if (granted) {
            enableLocationPlugin();
        } else {
            //Toast.makeText(this, R.string.user_location_permission_not_granted, Toast.LENGTH_LONG).show();
            finish();
        }
    }

    @Override
    @SuppressWarnings( {"MissingPermission"})
    public void onConnected() {
        locationEngine.requestLocationUpdates();
    }

    @Override
    public void onLocationChanged(Location location) {
        if (location != null) {
            setCameraPosition(location);
            locationEngine.removeLocationEngineListener(this);
        }
    }
}
```

**Comment by ShaldonSwiidAppDesigns** [comment]
Through extensive research and hours of errors, I finally figured the answer out through this thread [.](https://github.com/mapbox/mapbox-gl-native/issues/10484) I will close this matter now, but if anyone needs the answer to their issue. It can be found there.
