### ISSUE TITLE
[LocationLayer] crashing issue

### ISSUE THREAD

**Issue by mf-mindcrewtech** [mapbox/mapbox-android-demo#580]
I am using locationlayer to show my current location and when I [single/double] tap on map. App getting crashed with following errors.

NOTE :: My GPS is on and i am getting location.

java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.calculateZoomLevelRadius(LocationLayer.java:190)
at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayer.updateAccuracyRadius(LocationLayer.java:184)
at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.onCameraMove(LocationLayerPlugin.java:483)

**Comment by tobrun** [comment]
Could you open a issue on https://github.com/mapbox/mapbox-plugins-android for this? 
This repo is dedicated to mapbox-android-demo related issues.
