### ISSUE TITLE
Share snapshot image activity crashes

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#602]
Example crashes when the FAB is clicked

```
01-16 09:25:38.826 28521-28521/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.mapbox.mapboxandroiddemo.debug, PID: 28521
                                                                                    android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.mapbox.mapboxandroiddemo.debug/files/Pictures/share_image_1516123537332.png exposed beyond app through ClipData.Item.getUri()
                                                                                        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
                                                                                        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
                                                                                        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
                                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
                                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
                                                                                        at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
                                                                                        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:4495)
                                                                                        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                                        at android.app.Activity.startActivityForResult(Activity.java:4453)
                                                                                        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                                                                                        at android.app.Activity.startActivity(Activity.java:4814)
                                                                                        at android.app.Activity.startActivity(Activity.java:4782)
                                                                                        at com.mapbox.mapboxandroiddemo.examples.snapshot.SnapshotShareActivity$2.onSnapshotReady(SnapshotShareActivity.java:113)
                                                                                        at com.mapbox.mapboxsdk.snapshotter.MapSnapshotter$1.run(MapSnapshotter.java:435)
                                                                                        at android.os.Handler.handleCallback(Handler.java:789)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                        at android.os.Looper.loop(Looper.java:164)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-16 09:25:38.827 28521-28521/com.mapbox.mapboxandroiddemo.debug E/UncaughtException: android.os.FileUriExposedException: file:///storage/emulated/0/Android/data/com.mapbox.mapboxandroiddemo.debug/files/Pictures/share_image_1516123537332.png exposed beyond app through ClipData.Item.getUri()
                                                                                           at android.os.StrictMode.onFileUriExposed(StrictMode.java:1958)
                                                                                           at android.net.Uri.checkFileUriExposed(Uri.java:2348)
                                                                                           at android.content.ClipData.prepareToLeaveProcess(ClipData.java:941)
                                                                                           at android.content.Intent.prepareToLeaveProcess(Intent.java:9735)
                                                                                           at android.content.Intent.prepareToLeaveProcess(Intent.java:9741)
                                                                                           at android.content.Intent.prepareToLeaveProcess(Intent.java:9720)
                                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1795)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:4495)
                                                                                           at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:67)
                                                                                           at android.app.Activity.startActivityForResult(Activity.java:4453)
                                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:732)
                                                                                           at android.app.Activity.startActivity(Activity.java:4814)
                                                                                           at android.app.Activity.startActivity(Activity.java:4782)
                                                                                           at com.mapbox.mapboxandroiddemo.examples.snapshot.SnapshotShareActivity$2.onSnapshotReady(SnapshotShareActivity.java:113)
                                                                                           at com.mapbox.mapboxsdk.snapshotter.MapSnapshotter$1.run(MapSnapshotter.java:435)
                                                                                           at android.os.Handler.handleCallback(Handler.java:789)
                                                                                           at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                                           at android.os.Looper.loop(Looper.java:164)
                                                                                           at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                                           at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
01-16 09:25:38.833 28521-28545/com.mapbox.mapboxandroiddemo.debug E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
```

**Comment by langsmith** [comment]
https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by langsmith** [comment]
https://stackoverflow.com/questions/42251634/android-os-fileuriexposedexception-file-jpg-exposed-beyond-app-through-clipdata

**Comment by langsmith** [comment]
https://proandroiddev.com/sharing-files-though-intents-are-you-ready-for-nougat-70f7e9294a0b
