### ISSUE TITLE
Places plugin example crash

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#650]
![ezgif com-resize](https://user-images.githubusercontent.com/4394910/37214934-6e3f84b4-236b-11e8-9980-a6c778ad2785.gif)

The places plugin example crashes when the search fab button is tapped. It works fine if you install the app via `master` but it crashes when the app is downloaded from the Play Store.

cc @cammace 

```
03-09 07:22:47.026 5711-5711/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                 Process: com.mapbox.mapboxandroiddemo, PID: 5711
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxandroiddemo/com.mapbox.plugins.places.autocomplete.ui.PlaceAutocompleteActivity}: com.google.gson.JsonParseException: java.lang.ClassNotFoundException: com.mapbox.geojson.Point
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046)
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
                                                     at android.os.Handler.dispatchMessage(Handler.java:105)
                                                     at android.os.Looper.loop(Looper.java:164)
                                                     at android.app.ActivityThread.main(ActivityThread.java:6809)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                                                  Caused by: com.google.gson.JsonParseException: java.lang.ClassNotFoundException: com.mapbox.geojson.Point
                                                     at com.mapbox.d.b.e.a(Unknown Source:77)
                                                     at com.mapbox.d.b.e.deserialize(Unknown Source:0)
                                                     at com.google.gson.internal.bind.TreeTypeAdapter.read(Unknown Source:35)
                                                     at com.mapbox.b.b.a.a.f$a.a(Unknown Source:283)
                                                     at com.mapbox.b.b.a.a.f$a.read(Unknown Source:0)
                                                     at com.google.gson.Gson.fromJson(Unknown Source:20)
                                                     at com.google.gson.Gson.fromJson(Unknown Source:4)
                                                     at com.google.gson.Gson.fromJson(Unknown Source:9)
                                                     at com.google.gson.Gson.fromJson(Unknown Source:0)
                                                     at com.mapbox.b.b.a.a.i.a(Unknown Source:52)
                                                     at com.mapbox.plugins.places.autocomplete.viewmodel.PlaceAutocompleteViewModel.c(Unknown Source:37)
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.e(Unknown Source:2)
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.onActivityCreated(Unknown Source:43)
                                                     at android.support.v4.a.i.performActivityCreated(Unknown Source:15)
                                                     at android.support.v4.a.o.a(Unknown Source:685)
                                                     at android.support.v4.a.o.e(Unknown Source:32)
                                                     at android.support.v4.a.o.a(Unknown Source:46)
                                                     at android.support.v4.a.c.d(Unknown Source:169)
                                                     at android.support.v4.a.o.b(Unknown Source:41)
                                                     at android.support.v4.a.o.a(Unknown Source:103)
                                                     at android.support.v4.a.o.b(Unknown Source:97)
                                                     at android.support.v4.a.o.g(Unknown Source:21)
                                                     at android.support.v4.a.o.e(Unknown Source:10)
                                                     at android.support.v4.a.o.o(Unknown Source:4)
                                                     at android.support.v4.a.l.f(Unknown Source:4)
                                                     at android.support.v4.a.j.onStart(Unknown Source:22)
                                                     at android.support.v7.app.e.onStart(Unknown Source:0)
                                                     at com.mapbox.plugins.places.autocomplete.ui.PlaceAutocompleteActivity.onStart(Unknown Source:5)
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1412)
                                                     at android.app.Activity.performStart(Activity.java:7015)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.ClassNotFoundException: com.mapbox.geojson.Point
                                                     at java.lang.Class.classForName(Native Method)
                                                     at java.lang.Class.forName(Class.java:453)
                                                     at java.lang.Class.forName(Class.java:378)
                                                     at com.mapbox.d.b.e.a(Unknown Source:39)
                                                     at com.mapbox.d.b.e.deserialize(Unknown Source:0) 
                                                     at com.google.gson.internal.bind.TreeTypeAdapter.read(Unknown Source:35) 
                                                     at com.mapbox.b.b.a.a.f$a.a(Unknown Source:283) 
                                                     at com.mapbox.b.b.a.a.f$a.read(Unknown Source:0) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:20) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:4) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:9) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:0) 
                                                     at com.mapbox.b.b.a.a.i.a(Unknown Source:52) 
                                                     at com.mapbox.plugins.places.autocomplete.viewmodel.PlaceAutocompleteViewModel.c(Unknown Source:37) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.e(Unknown Source:2) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.onActivityCreated(Unknown Source:43) 
                                                     at android.support.v4.a.i.performActivityCreated(Unknown Source:15) 
                                                     at android.support.v4.a.o.a(Unknown Source:685) 
                                                     at android.support.v4.a.o.e(Unknown Source:32) 
                                                     at android.support.v4.a.o.a(Unknown Source:46) 
                                                     at android.support.v4.a.c.d(Unknown Source:169) 
                                                     at android.support.v4.a.o.b(Unknown Source:41) 
                                                     at android.support.v4.a.o.a(Unknown Source:103) 
                                                     at android.support.v4.a.o.b(Unknown Source:97) 
                                                     at android.support.v4.a.o.g(Unknown Source:21) 
                                                     at android.support.v4.a.o.e(Unknown Source:10) 
                                                     at android.support.v4.a.o.o(Unknown Source:4) 
                                                     at android.support.v4.a.l.f(Unknown Source:4) 
                                                     at android.support.v4.a.j.onStart(Unknown Source:22) 
                                                     at android.support.v7.app.e.onStart(Unknown Source:0) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.PlaceAutocompleteActivity.onStart(Unknown Source:5) 
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1412) 
                                                     at android.app.Activity.performStart(Activity.java:7015) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.geojson.Point" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo-v6AoEoASZcCbIezjBZjqBw==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo-v6AoEoASZcCbIezjBZjqBw==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo-v6AoEoASZcCbIezjBZjqBw==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                     at java.lang.Class.classForName(Native Method) 
                                                     at java.lang.Class.forName(Class.java:453) 
                                                     at java.lang.Class.forName(Class.java:378) 
                                                     at com.mapbox.d.b.e.a(Unknown Source:39) 
                                                     at com.mapbox.d.b.e.deserialize(Unknown Source:0) 
                                                     at com.google.gson.internal.bind.TreeTypeAdapter.read(Unknown Source:35) 
                                                     at com.mapbox.b.b.a.a.f$a.a(Unknown Source:283) 
                                                     at com.mapbox.b.b.a.a.f$a.read(Unknown Source:0) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:20) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:4) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:9) 
                                                     at com.google.gson.Gson.fromJson(Unknown Source:0) 
                                                     at com.mapbox.b.b.a.a.i.a(Unknown Source:52) 
                                                     at com.mapbox.plugins.places.autocomplete.viewmodel.PlaceAutocompleteViewModel.c(Unknown Source:37) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.e(Unknown Source:2) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.a.onActivityCreated(Unknown Source:43) 
                                                     at android.support.v4.a.i.performActivityCreated(Unknown Source:15) 
                                                     at android.support.v4.a.o.a(Unknown Source:685) 
                                                     at android.support.v4.a.o.e(Unknown Source:32) 
                                                     at android.support.v4.a.o.a(Unknown Source:46) 
                                                     at android.support.v4.a.c.d(Unknown Source:169) 
                                                     at android.support.v4.a.o.b(Unknown Source:41) 
                                                     at android.support.v4.a.o.a(Unknown Source:103) 
                                                     at android.support.v4.a.o.b(Unknown Source:97) 
                                                     at android.support.v4.a.o.g(Unknown Source:21) 
                                                     at android.support.v4.a.o.e(Unknown Source:10) 
                                                     at android.support.v4.a.o.o(Unknown Source:4) 
                                                     at android.support.v4.a.l.f(Unknown Source:4) 
                                                     at android.support.v4.a.j.onStart(Unknown Source:22) 
                                                     at android.support.v7.app.e.onStart(Unknown Source:0) 
                                                     at com.mapbox.plugins.places.autocomplete.ui.PlaceAutocompleteActivity.onStart(Unknown Source:5) 
                                                     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1412) 
                                                     at android.app.Activity.performStart(Activity.java:7015) 
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2909) 
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3046) 
                                                     at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:105) 
                                                     at android.os.Looper.loop(Looper.java:164) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:6809) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by cammace** [comment]
These crashes are coming from ProGuard. If you build a local release build and run it, it will result in the same issue. I need to add a consumer ProGuard file to place plugin to ensure these models don't get stripped out.

**Comment by langsmith** [comment]
ok, thanks

**Comment by langsmith** [comment]
I'm assuming that https://github.com/mapbox/mapbox-plugins-android/pull/373 and @cammace 's next release of the places plugin will fix this issue.
