### ISSUE TITLE
GeoJSON plugin crash

### ISSUE THREAD

**Issue by langsmith** [mapbox/mapbox-android-demo#673]
GeoJSON plugin example loads fine but crashes when GeoJSON is loaded via asset folder or downloaded from a working URL. This is while using the 6.0.0-beta.6 version of the Mapbox Maps SDK for Android. Discovered while working on #663 . 

Looks like an outdated `FeatureCollection` import issue with the plugin? cc/fyi @cammace 

```
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/commons/geojson/FeatureCollection;
```

```
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.services.commons.geojson.FeatureCollection" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
```

💥:

```
    --------- beginning of crash
04-05 14:52:57.427 7730-7868/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
    Process: com.mapbox.mapboxandroiddemo.debug, PID: 7730
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/commons/geojson/FeatureCollection;
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.parseGeoJsonString(GeoJsonPlugin.java:307)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.access$700(GeoJsonPlugin.java:64)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:205)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:202)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.services.commons.geojson.FeatureCollection" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.parseGeoJsonString(GeoJsonPlugin.java:307) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.access$700(GeoJsonPlugin.java:64) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:205) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:202) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
04-05 14:52:57.428 7730-7868/com.mapbox.mapboxandroiddemo.debug E/UncaughtException: java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:353)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/mapbox/services/commons/geojson/FeatureCollection;
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.parseGeoJsonString(GeoJsonPlugin.java:307)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.access$700(GeoJsonPlugin.java:64)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:205)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:202)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.mapbox.services.commons.geojson.FeatureCollection" on path: DexPathList[[zip file "/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/lib/arm64, /data/app/com.mapbox.mapboxandroiddemo.debug-wilGCIqfjF4iobNznmzSbQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.parseGeoJsonString(GeoJsonPlugin.java:307) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin.access$700(GeoJsonPlugin.java:64) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:205) 
        at com.mapbox.mapboxsdk.plugins.geojson.GeoJsonPlugin$ParseGeoJsonFromString.doInBackground(GeoJsonPlugin.java:202) 
        at android.os.AsyncTask$2.call(AsyncTask.java:333) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) 
        at java.lang.Thread.run(Thread.java:764) 
04-05 14:52:57.434 7730-7772/com.mapbox.mapboxandroiddemo.debug E/FA: Missing google_app_id. Firebase Analytics disabled. See https://goo.gl/NAOOOI
04-05 14:52:57.692 7730-7868/com.mapbox.mapboxandroiddemo.debug D/AppTracker: App Event: crash
04-05 14:52:57.697 7730-7872/com.mapbox.mapboxandroiddemo.debug I/FirebaseCrash: Sending crashes
```

**Comment by langsmith** [comment]
Example was recently removed from app.
