### ISSUE TITLE
AnimatedImageGifActivity is crashing

### ISSUE THREAD

**Issue by LukasPaczos** [mapbox/mapbox-android-demo#828]
`AnimatedImageGifActivity` is not displaying the raster source and is crashing if we close the activity before the map is loaded.

**Comment by LukasPaczos** [comment]
The `handler` is initialized only [when the map is loaded](https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/AnimatedImageGifActivity.java#L75), so if you close the activity before the callback fires, you'll get a `NPE` from the `onStop`. I didn't analyze it further and not sure why the bear was not showing up.

**Comment by LukasPaczos** [comment]
Not sure if it's still the same issue, but I've got the stack trace:
```
2019-04-10 18:53:39.283 26437-26437/com.mapbox.mapboxandroiddemo.debug E/Mbgl-MapChangeReceiver: Exception in onDidFinishLoadingStyle
    java.lang.IllegalArgumentException: Failed to decode image. The resource provided must be a Bitmap.
        at com.mapbox.mapboxsdk.style.sources.ImageSource.setImage(ImageSource.java:123)
        at com.mapbox.mapboxsdk.style.sources.ImageSource.<init>(ImageSource.java:78)
        at com.mapbox.mapboxandroiddemo.examples.labs.AnimatedImageGifActivity$1.onStyleLoaded(AnimatedImageGifActivity.java:61)
        at com.mapbox.mapboxsdk.maps.MapboxMap.notifyStyleLoaded(MapboxMap.java:846)
        at com.mapbox.mapboxsdk.maps.MapboxMap.onFinishLoadingStyle(MapboxMap.java:206)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onDidFinishLoadingStyle(MapView.java:1178)
        at com.mapbox.mapboxsdk.maps.MapChangeReceiver.onDidFinishLoadingStyle(MapChangeReceiver.java:194)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onDidFinishLoadingStyle(NativeMapView.java:1031)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:326)
        at android.os.Looper.loop(Looper.java:160)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
