### ISSUE TITLE
NPE in CalendarIntegrationActivity

### ISSUE THREAD

**Issue by osana** [mapbox/mapbox-android-demo#847]
Got a crash while running labs Calendar integration Activity

08-31 13:27:40.654 31967-31967/com.mapbox.mapboxandroiddemo.debug E/Mbgl-NativeMapView: Exception in MapView.OnMapChangedListener
    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.isEmpty()' on a null object reference
        at com.mapbox.mapboxandroiddemo.examples.labs.CalendarIntegrationActivity.getCalendarData(CalendarIntegrationActivity.java:163)
        at com.mapbox.mapboxandroiddemo.examples.labs.CalendarIntegrationActivity.onMapReady(CalendarIntegrationActivity.java:96)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapReady(MapView.java:1232)
        at com.mapbox.mapboxsdk.maps.MapView$MapCallback.onMapChanged(MapView.java:1217)
        at com.mapbox.mapboxsdk.maps.NativeMapView.onMapChanged(NativeMapView.java:907)
     

Adding an extra check for null should fix the problem: 

https://github.com/mapbox/mapbox-android-demo/blob/e57973ac6eabe0033bb5d0cf6570f46091e1f14a/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/labs/CalendarIntegrationActivity.java#L163

**Comment by langsmith** [comment]
thanks @osana
