### ISSUE TITLE
Build Issue with mapbox-android-demo

### ISSUE THREAD

**Issue by mcprakash** [mapbox/mapbox-android-demo#914]
Build error on activityTracker.java (Lines 63 and 65). New to Android and MapBox. Please help
![screenshot from 2018-11-15 22-36-14](https://user-images.githubusercontent.com/8052668/48569246-30693e00-e927-11e8-883e-4b21bd523ae5.png)

**Comment by langsmith** [comment]
hey @mcprakash , thanks for your interest in Mapbox! This is something that I need to fix. 

For now, you don't need to worry about `AnalyticsTracker`. You can replace the `Analytics.builder(context.getString(R.string.mapbox_segment_wearable_write_key)).build();` line with 
`Analytics.builder("").build();`

You can replace `Analytics.builder(context.getString(R.string.mapbox_segment_write_key)).build();` with `Analytics.builder("").build();`. 

or, your other option for fixing this is to find the `strings.xml` file and paste:

```xml
<string name="mapbox_segment_write_key"></string>
<string name="mapbox_segment_wearable_write_key"></string>
```

into the `strings.xml` file. Your `strings.xml` file should look like:

```xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
<string name="mapbox_auth_flow_secret"></string>
<string name="mapbox_segment_write_key"></string>
<string name="mapbox_segment_wearable_write_key"></string>
<string name="access_token">PASTE_YOUR_MAPBOX_ACCESS_TOKEN_HERE</string>

</resources>
```

If you're still having issues, let me know.

**Comment by mcprakash** [comment]
Hi @langsmith 
 Thank you for the above note. 
 
Just for future ref
-> Error on Line 80 AccountRetrievalService.java 
![screenshot from 2018-11-15 23-59-53](https://user-images.githubusercontent.com/8052668/48573716-1df50180-e933-11e8-829a-024d732eb582.png)

->Next Error
 `org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':MapboxAndroidDemo:transformClassesAndResourcesWithProguardForChinaRelease'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:103)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:73)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:256)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:249)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:238)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:663)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:597)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Job failed, see logs for details
	at com.android.build.gradle.internal.transforms.ProGuardTransform.transform(ProGuardTransform.java:196)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.GeneratedMethodAccessor403.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:124)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:113)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:95)
	... 33 more
Caused by: java.io.IOException: Please correct the above warnings first.
	at proguard.Initializer.execute(Initializer.java:473)
	at proguard.ProGuard.initialize(ProGuard.java:233)
	at proguard.ProGuard.execute(ProGuard.java:98)
	at com.android.build.gradle.internal.transforms.BaseProguardAction.runProguard(BaseProguardAction.java:61)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.doMinification(ProGuardTransform.java:253)
	at com.android.build.gradle.internal.transforms.ProGuardTransform.access$000(ProGuardTransform.java:63)
	at com.android.build.gradle.internal.transforms.ProGuardTransform$1.run(ProGuardTransform.java:173)
	at com.android.builder.tasks.Job.runTask(Job.java:47)
	at com.android.build.gradle.tasks.SimpleWorkQueue$EmptyThreadContext.runTask(SimpleWorkQueue.java:41)
	at com.android.builder.tasks.WorkQueue.run(WorkQueue.java:282)
	... 1 more
`

**Comment by langsmith** [comment]
yep, thanks for the suggestion and info @mcprakash 🤝

**Comment by mcprakash** [comment]
Hi @langsmith, After yesterday's build by @Chaoba , no errors on Android studio. The only issue is that by default the China flavor is being built and I do not see any examples in any of the categories. I am currently in India. It would be great to know how to change it to the ` main` or `international` versions. Thanks

**Comment by Chaoba** [comment]
Hi @mcprakash , you can click the "Build Variants" on the left bottom of your Android studio, then chose "globalDebug" to change the flavor to global.
![image](https://user-images.githubusercontent.com/8577318/48602340-c778d900-e9ad-11e8-89c2-b18dc9a50909.png)

**Comment by mcprakash** [comment]
Hi @langsmith 
 Thanks, it works now. Just a final question, I am trying to tap into notifications (say about 50 meters before a new event or so). Could you let me know what would be the best way to get to this ? Also, it there is a forum to get help, it would be great. And one more thing is that the app gets stuck in Loading and never goes beyond that. Waited for 30 min. 
![screenshot_20181116-135543_mapbox demo](https://user-images.githubusercontent.com/8052668/48609220-71099b80-e9a9-11e8-8abb-98f55251f9a1.jpg)

Thanks 
Chandra

**Comment by langsmith** [comment]
Hm, that's weird about the loading screen. You can ignore/skip the loading that. You don't _have_ to sign into your Mapbox account to use the demo app.

>I am trying to tap into notifications (say about 50 meters before a new event or so)

I'm not sure what you mean by this.

https://github.com/mapbox/mapbox-android-demo/blob/master/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/snapshot/SnapshotNotificationActivity.java shows you can fire a notification with a map image in it. 

This is more of a help/support question, rather than an issue with the demo app. Please use https://www.mapbox.com/contact/support/#products/android so that the rest of our team can help you out.

**Comment by tazik561** [comment]
Thank's @Chaoba .It is work
