### ISSUE TITLE
Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView

### ISSUE THREAD

**Issue by tazik561** [mapbox/mapbox-android-demo#975]
I am trying to learn mapbox by your git library.After download and open in android studio and add my map_key i am trying to run on emulator.After opening app in emulator when i open navigation drawer and select for example "**style**" and choose "**Change a layer's color**" I got this error:

`        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: **Binary XML file line #88: Binary XML file line #88: Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView**
     Caused by: android.view.InflateException: **Binary XML file line #88: Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView**
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        **at com.mapbox.mapboxandroiddemo.examples.styles.ColorSwitcherActivity.onCreate(ColorSwitcherActivity.java:40)**
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)`

Why it is not possible to inflate xml layout? and what is happening?

**Comment by langsmith** [comment]
Hey @tazik561 , you probably installed the `china` build variant, rather than `global`. You want the `global` flavor. See https://github.com/mapbox/mapbox-android-demo/issues/914#issuecomment-439298105 for instructions on how to change the build variant. The `global` variant should work with your Mapbox access token. If you still have issues, let me know! Thanks for looking into Mapbox!
