### ISSUE TITLE
ColorSwitcherActivity Inflate Exception

### ISSUE THREAD

**Issue by riastrad** [mapbox/mapbox-android-demo#986]
`ColorSwitcherActivity` is crashing with a RuntimeException when you attempt to open it. This when running the app built from source on the master branch. 

![demoappcrash](https://user-images.githubusercontent.com/16272584/53896446-0cc72200-4002-11e9-8191-9f9c083cbcc4.gif)

<details>
  <summary>Logcat</summary>
  <pre>
  2019-03-06 11:03:32.488 14051-14051/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.mapbox.mapboxandroiddemo.debug, PID: 14051
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mapbox.mapboxandroiddemo.debug/com.mapbox.mapboxandroiddemo.examples.styles.ColorSwitcherActivity}: android.view.InflateException: Binary XML file line #88: Binary XML file line #88: Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2951)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: android.view.InflateException: Binary XML file line #88: Binary XML file line #88: Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView
     Caused by: android.view.InflateException: Binary XML file line #88: Error inflating class com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:469)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:140)
        at com.mapbox.mapboxandroiddemo.examples.styles.ColorSwitcherActivity.onCreate(ColorSwitcherActivity.java:40)
        at android.app.Activity.performCreate(Activity.java:7144)
        at android.app.Activity.performCreate(Activity.java:7135)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3086)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1816)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
2019-03-06 11:03:32.488 14051-14051/com.mapbox.mapboxandroiddemo.debug E/AndroidRuntime: Caused by: java.lang.NoSuchMethodError: No virtual method getStyleUrl()Ljava/lang/String; in class Lcom/mapbox/mapboxsdk/maps/MapboxMapOptions; or its super classes (declaration of 'com.mapbox.mapboxsdk.maps.MapboxMapOptions' appears in /data/app/com.mapbox.mapboxandroiddemo.debug-FWBJVoaPO3g-tp-kVeakfw==/base.apk!classes3.dex)
        at com.mapbox.mapboxsdk.plugins.china.maps.MapboxMapChinaOptions.convert(MapboxMapChinaOptions.java:23)
        at com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView.initialize(ChinaMapView.java:38)
        at com.mapbox.mapboxsdk.maps.MapView.<init>(MapView.java:100)
        at com.mapbox.mapboxsdk.plugins.china.maps.ChinaMapView.<init>(ChinaMapView.java:23)
        	... 28 more
</pre>
</details>

**Comment by riastrad** [comment]
https://github.com/mapbox/mapbox-android-demo/issues/914#issuecomment-439298105

Please disregard. 🤦‍♂️
